FIP-55
fei-protocol/fei-protocol-core pull request #353
Opened 2021-12-05 01:30 UTC by Joeysantoro

2021-12-06 11:54 UTC, ditchfieldcaleb requested changes
Needs an integration test or two, otherwise good.

2021-12-06 11:54 UTC, ditchfieldcaleb commented on proposals/dao/fip_55.ts
> +} from '../../types/types';
use shorthand

2021-12-06 11:56 UTC, ditchfieldcaleb commented
@Joeysantoro I think we should add in a check when withdrawing to a safe address *other than the DAOTimelock* that the source and destination underlying token is the same. Otherwise, we could accidentally burn tokens by transferring them into a pcv deposit that can't handle them.

2021-12-06 11:59 UTC, ditchfieldcaleb commented
Also there's an e2e test on this that is failing that I'd like to see fixed before approving.

2021-12-06 14:36 UTC, eswak approved these changes

2021-12-06 14:37 UTC, eswak commented
> @Joeysantoro I think we should add in a check when withdrawing to a safe address _other than the DAOTimelock_ that the source and destination underlying token is the same. Otherwise, we could accidentally burn tokens by transferring them into a pcv deposit that can't handle them.

We shouldn't be able to burn tokens this way, because deposits have a `withdrawERC20` function

2021-12-06 18:26 UTC, Joeysantoro commented
> @Joeysantoro I think we should add in a check when withdrawing to a safe address _other than the DAOTimelock_ that the source and destination underlying token is the same. Otherwise, we could accidentally burn tokens by transferring them into a pcv deposit that can't handle them.

Interesting. I think we need to sync on this because at a glance its a good idea but it removes the flexibility to rely on withdrawERC20. I think we should put this check inside the `depositAfter` logic

2021-12-06 18:43 UTC, ElliotFriedman commented on proposals/dao/fip_55.ts
> +  const pcvGuardian: PCVGuardian = contracts.pcvGuardian as PCVGuardian;
We shouldn't need to cast to type of PCVGuardian as the artifact that is loaded from contracts should be correct.

2021-12-07 19:45 UTC, ElliotFriedman commented on test/integration/tests/pcv.ts
> +      expect(await contracts.fei.balanceOf(contractAddresses.feiDAOTimelock)).to.be.bignumber.equal(
We should add test to see delta between starting and ending balance.

2021-12-07 19:46 UTC, ditchfieldcaleb approved these changes

2021-12-07 20:24 UTC, merged