V2 Main Deploy
fei-protocol/fei-protocol-core pull request #354
Opened 2021-12-05 04:16 UTC by Joeysantoro

Deploys TRIBE Minter and Backstop

2021-12-05 07:25 UTC, ditchfieldcaleb commented
hype af, lfggg

2021-12-05 07:26 UTC, ditchfieldcaleb commented on proposals/dao/backstop.ts
> +} from '../../types/types';
use relative path

2021-12-05 20:17 UTC, Joeysantoro commented on proposals/dao/backstop.ts
> +} from '../../types/types';
done

2021-12-06 14:30 UTC, eswak approved these changes

2021-12-07 19:40 UTC, ElliotFriedman commented
LGTM!

2021-12-07 19:49 UTC, ditchfieldcaleb requested changes
Will approve once e2e test is fixed & merge conflict is fixed.

2021-12-07 20:39 UTC, ditchfieldcaleb approved these changes

2021-12-07 21:24 UTC, merged