redeemer
fei-protocol/fei-protocol-core pull request #463
Opened 2022-01-13 23:03 UTC by Joeysantoro

2022-01-14 22:56 UTC, ElliotFriedman commented on contracts/merger/REPTbRedeemer.sol
> +        emit Exchange(msg.sender, to, amount);
as long as exchange rate is 1:1 this looks good

2022-01-14 22:58 UTC, ditchfieldcaleb approved these changes

2022-01-14 23:46 UTC, ElliotFriedman requested changes

2022-01-14 23:46 UTC, ElliotFriedman commented on proposals/description/fip_redeem.ts
> +      description: 'Expire peg exchanger'
we need a wrapper contract so this is reported as protocol FEI when it is sitting in the peg reptbRedeemer

2022-01-14 23:46 UTC, ElliotFriedman approved these changes

2022-01-17 16:42 UTC, ElliotFriedman approved these changes

2022-01-17 21:26 UTC, ElliotFriedman approved these changes

2022-01-17 21:46 UTC, merged