Fei Docs
fei-protocol/fei-protocol-core pull request #700
Opened 2022-04-14 16:08 UTC by thomas-waite

# Summary
Adds Fei Docs. Based on Github pages and created from the `/docs` directory.

Expected that in the future that the docs are updated simultaneously when new features are added/changed.

2022-04-14 22:32 UTC, ElliotFriedman requested changes

2022-04-14 22:32 UTC, ElliotFriedman commented on docs/protocol/Security.md
> +Fei Protocol needs to protect against malicious actors and attack that come in multiple categories. We attempt to firewall assets from each other as best as possible, so that exploits in one area don
`retroactively`, not `retractively`

2022-04-14 22:32 UTC, ElliotFriedman commented on docs/protocol/Security.md
> +# Protocol Security
Should add a section here that talks about roles within the system and how we assume that the governor is not acting maliciously, similar to yearn's section on this role https://docs.yearn.finance/security/index#security-assumption

2022-04-14 22:32 UTC, ElliotFriedman commented on docs/protocol/PCVDeposits.md
> +For instance, an `ERC20CompoundPCVDeposit` ([link]([aaaa](https://github.com/fei-protocol/fei-protocol-core/blob/develop/contracts/pcv/compound/ERC20CompoundPCVDeposit.sol))) can deposit and withdraw
`[aaaa]`?

2022-04-14 22:32 UTC, ElliotFriedman commented on contracts/external/WETH9.sol
> -/**
Removing this contract causes tests to break. Either remove the failing tests as well, or add this contract back.

2022-04-14 22:37 UTC, ElliotFriedman commented
Overall, things look really good here, will be great to get these improved docs up!

2022-04-20 23:07 UTC, thomas-waite commented
Closing as now in a seperate repo here: https://github.com/fei-protocol/docs and using docusaurus rather than github pages

2022-04-20 23:07 UTC, closed without merging