Slowly liquidate CREAM
fei-protocol/fei-protocol-core pull request #802
Opened 2022-05-13 18:18 UTC by thomas-waite

# Summary
Makes use of the `PCVSwapperUniswap` contract to slowly liquidate CREAM over time

2022-05-16 15:46 UTC, ElliotFriedman requested changes

2022-05-16 20:28 UTC, thomas-waite commented on contracts/pcv/uniswap/FeiRouter.sol
> +        require(amountOut >= amountOutMin, "FeiRouter: Insufficient output amount");
This PR is very much WIP and not ready for review. I open prematurely in general and attach WIP to show what I'm working on. 

This contract was copied over from a historic branch that I'm using. It's being removed and isn't needed

2022-05-17 19:09 UTC, thomas-waite commented on contracts/pcv/uniswap/PCVSwapperUniswap.sol
> +        _incentivize();
Note: This won't be used, not granting this contract minting priviledges

2022-05-18 09:21 UTC, eswak commented on contracts/pcv/uniswap/PCVSwapperUniswap.sol
> +        Decimal.D256 memory oracleAmountOut = twap.mul(amountIn);
be careful about this, most oracles report an USD value, so the "token out" has to be a USD token. Or if oracle reports in ETH value, "token out" has to be in ETH. Easy to misconfigure things around oracles there, we'll need to be very careful in proposal validation scripts when using swappers

2022-05-20 12:28 UTC, closed without merging